package dev.let.agentic.domain;

public enum AuditType {
    RUN_STARTED, STAGE_STARTED, STAGE_SUCCEEDED, STAGE_FAILED, STAGE_RETRY,
    STAGE_SKIPPED, STAGE_INVALIDATED, APPROVAL_REQUESTED, APPROVED, REJECTED,
    ROLLBACK, SAFE_STOP, POLICY_VIOLATION, RUN_DONE, RUN_FAILED
}
