package dev.let.agentic.domain;

public enum StageId {
    REQUIREMENT, CLARIFY, IMPACT, PLANNING,
    ARCHITECTURE, SECURITY, DATA_API,
    DESIGN_APPROVAL, IMPLEMENTATION, TESTS, DOCS,
    VALIDATION, RELEASE_APPROVAL, RELEASE
}
